### ISSUE TITLE
[Stable Diffusion1_5][WebNN GPU] Failed to execute 'add' on 'MLGraphBuilder': The input operand data types don't match.

### ISSUE THREAD

**Issue by JiangYueBook** [microsoft/webnn-developer-preview#16]
**Repro Steps:**

1. Launch latest Chrome Canary on Windows 11  
  C:\Users\AppData\Local\Google\Chrome SxS\Application\chrome.exe" --enable-features=WebMachineLearningNeuralNetwork
  
2. Visit https://microsoft.github.io/webnn-developer-preview/demos/stable-diffusion-1.5/
  
3. Click Load Models button.
  

**Actual Result:**

   TypeError: Failed to execute 'add' on 'MLGraphBuilder': The input operand data types don't match. (The error occur when text encode begin to create session.)

**Environment:**

Chrome Canary: 128.0.6600.0 (Official Build)

GPU Driver Version: 32.0.101.5762

| Device | OS  | CPU | GPU |
| --- | --- | --- | --- |
| Laptop | Windows 11 23H2 | Ultra 7 155H | Intel Arc Graphics |

**Comment by ibelem** [comment]
Caused by argMax change: [chromium-review.googlesource.com/c/chromium/src/+/5692538](https://chromium-review.googlesource.com/c/chromium/src/+/5692538)

**Comment by huningxin** [comment]
> Caused by argMax change: [chromium-review.googlesource.com/c/chromium/src/+/5692538](https://chromium-review.googlesource.com/c/chromium/src/+/5692538)

Yes, this is caused by [argMax default output data type is "int32"](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/ml/webnn/ml_graph_builder.idl;l=29?q=graph_builder.idl&ss=chromium) in Chromium prototype now. WebNN EP should set the newly introduced `MLArgMinMaxOptions.outputDataType` to "int64" for [ONNX ArgMax whose output is "int64"](https://onnx.ai/onnx/operators/onnx__ArgMax.html#outputs).

@Honry has a fix for WebNN EP: https://github.com/microsoft/onnxruntime/pull/21385

@philloooo, would you plan to send a spec change?

/cc @fdwr

**Comment by fdwr** [comment]
WebNN spec update is here: https://github.com/webmachinelearning/webnn/pull/724/files
